name: Build Windows Executable

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'config/**'
      - '.github/workflows/windows-build.yml'
      - 'scripts/windows/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --name RadarDistanceMonitor src\radar_distance_monitor.py

      - name: Prepare bundle
        shell: bash
        run: |
          mkdir -p bundle
          cp dist/RadarDistanceMonitor.exe bundle/
          cp config/config_example.py bundle/
          cp scripts/windows/start.bat bundle/
          cp README.md bundle/README-WINDOWS.txt
          cd bundle && zip -r radar-distance-windows.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radar-distance-windows
          path: bundle/radar-distance-windows.zip


