name: Build Windows Executable

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'config/**'
      - '.github/workflows/windows-build.yml'
      - 'scripts/windows/**'
  workflow_dispatch:
  
# Note: This workflow builds Windows executables on every push to main.
# For release builds with both platforms, use the multi-platform-build workflow.

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --name RadarDistanceMonitor src\radar_distance_monitor.py

      - name: Prepare bundle
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path bundle
          Copy-Item dist/RadarDistanceMonitor.exe bundle/
          Copy-Item config/config_example.py bundle/
          Copy-Item scripts/windows/start.bat bundle/
          Copy-Item README.md bundle/README-WINDOWS.txt
          Compress-Archive -Path bundle/* -DestinationPath bundle/radar-distance-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radar-distance-windows
          path: bundle/radar-distance-windows.zip


